# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='mealday',
            old_name='meal_day',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='mealday',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.MealDay'),
            preserve_default=False,
        ),
    ]
